// Generated by CoffeeScript 2.0.0-beta2
(function() {
  var Package, Unit, glob, package_, path, stringify, unit_, winston;

  path = require('path');

  glob = require('glob');

  winston = require('winston');

  stringify = require('json-stringify-safe');

  ({unit_, Unit} = require('./unit'));


  /*
  This has a lot of commonality with Project.  Merge?
   */

  Package = class Package extends Unit {
    constructor(parent) {
      super(parent);
    }

    inject(k, v) {
      switch (k) {
        case 'blah':
          return this.log('blah');
        default:
          return super.inject(k, v);
      }
    }

  };

  exports.Package = Package;

  exports.package_ = package_ = function(cfg, parent) {
    return new Package(parent).config(cfg);
  };

}).call(this);

//# sourceMappingURL=package.js.map
